spring.application.name=smart-hostel

spring.datasource.url=jdbc:postgresql://db.xmekxsxqiykiqeouigbd.supabase.co:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=Bhargav2005Abc

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


server.port=${PORT:8080}